[storage] update to rocksdb 21.0 due to compilation issues (#8407)
had to update diesel as well due to some strange quirks:

```
error[E0277]: the trait bound `FieldAttr: ToTokens` is not satisfied
   -->
/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.0/src/attrs.rs:143:6
    |
143 | impl Spanned for FieldAttr {
    |      ^^^^^^^ the trait `ToTokens` is not implemented for
`FieldAttr`
    |
```