Changed "AptosCoin" to "TestCoin"
"0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>" gives an error for this tutorial (panicked at 'called `Option::unwrap()` on a `None` value'), it needs to be changed to "0x1::coin::CoinStore<0x1::test_coin::TestCoin>" in order for it to work.