Update transfer-coin.rs example to use Testnet
Devnet appears to fail with:

Error: Failed to get Alice's account balance

Caused by:
    0: Failed to get account balance
    1: API error Error(ResourceNotFound): Resource not found by Address(0x3a5c...), Struct tag(0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>) and Ledger version(109514525)