[move] Appease doc tests with move-analyzer library
When running the CI test command:

```
cargo xtest --doc --jobs ${max_threads} --unit --changed-since "origin/$TARGET_BRANCH"
```

The move-analyzer package would fail with the message:

```
error: no library targets found in package `move-analyzer`
```

Add a placeholder library target to fix the error.

Closes: #9379