[forge] Print helpful error when you cannot find helm chart
Check for the existence of helm chart before running helm and bailing with an unhelpful error message.

Test Plan:

```
2022-07-13T18:08:22.927269Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:338 aptos-node resources for Forge removed in namespace: forge-banana
Failed to run tests:
Helm chart terraform/helm/genesis does not exist, try running from the repo root
Error: Helm chart terraform/helm/genesis does not exist, try running from the repo root
$ cargo run -p forge-cli -- test k8s-swarm \
        --image-tag $IMAGE_TAG \
        --namespace $NAMESPACE \
        --port-forward
```