Fix error return format in init.rs
We were returning `            return Err(
                "For testnet, start over and run movement init --skip-faucet");`

which compiled locally for me, but I noticed it caused CI to fail [this job](https://github.com/movementlabsxyz/movement/pull/506) with error

```
   Compiling aptos-node v0.0.0-main (/home/runner/actions-runner/_work/movement/movement/aptos-core/aptos-node)
error[E0308]: mismatched types
   --> crates/aptos/src/common/init.rs:130:24
    |
130 |             return Err("For testnet, start over and run movement init --skip-faucet");
    |                    --- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `CliError`, found `&str`
    |                    |
    |                    arguments to this enum variant are incorrect
    |
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> crates/aptos/src/common/init.rs:130:20
    |
130 |             return Err("For testnet, start over and run movement init --skip-faucet");
    |                    ^^^^-------------------------------------------------------------^
    |                        |
    |                        this argument influences the type of `Err`
```

It looks like we need to specify the arg type, hence this fix.